services:
  web:
    build:
      context: ./../
      dockerfile: ./docker/dockerfile-backend
      tags:
        - wusabinga/projekt-backend:${VERSION}
        - wusabinga/projekt-backend:latest
    ports:
      - '3000:3000'

  mysql:
    build:
      context: ./../
      dockerfile: ./docker/dockerfile-mysql
      tags:
        - wusabinga/projekt-mysql:latest
    ports:
      - '3306:3306'
    volumes:
      - ../db-data:/var/lib/mysql
