apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-projekt
  namespace: guestbook
  labels:
    app: mysql-projekt
spec:
  selector:
    matchLabels:
      app: mysql-projekt
  replicas: 1
  template:
    metadata:
      labels:
        app: mysql-projekt
    spec:
      containers:
        - name: mysql-projekt
          image: wusabinga/projekt-mysql:latest
          env:
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: guestbook-secret
                  key: MYSQL-USER
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: guestbook-secret
                  key: MYSQL-ROOT-PASSWORD
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: guestbook-secret
                  key: MYSQL-PASSWORD
            - name: MYSQL_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: mysql-config
                  key: MYSQL_DATABASE
          ports:
            - containerPort: 3306
              name: mysql-port
