apiVersion: v1
kind: Service
metadata:
  name: guestbook-mysql
  namespace: guestbook
spec:
  selector:
    app: mysql-projekt
  type: ClusterIP
  ports:
    - name: mysql-projekt
      protocol: TCP
      port: 3306
      targetPort: mysql-port
