name: 'DevOps Demo Projkt Pipeline'
on:
  push:
    branches:
      - '**'
  workflow_dispatch:

jobs:
  Create-Docker-Images:
    name: Building Docker Images
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: check current work directory
        run: ls
