name: 'DevOps Demo Projkt Pipeline'
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  Create-Docker-Images:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: check current work directory
        run: ls
