name: 'DevOps Demo Projkt Pipeline'
on:
  push:
    branches:
      - '**'
  workflow_dispatch:

jobs:
  Create-Docker-Images:
    name: Building Docker Images
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: check current work directory
        run: ls
      - name: Installiere Node
        uses: actions/setup-node@v4
      - name: Install dependencies
        run: npm install -y
        working-directory: ./app/backend/
      - name: Check Lint style
        run: npm run lint
        working-directory: ./app/backend/
      - name: Run Tests
        run: npm run test
        working-directory: ./app/backend/
      - name: Build Docker Image
        run: docker-compose-build.sh
        working-directory: scripts/
